# Generated by Django 5.2.12 on 2026-04-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
            ],
            options={"ordering": ["nome"],},
        ),
        migrations.CreateModel(
            name="Progetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "ricorrenza",
                    models.CharField(
                        choices=[("annuale", "Annuale"), ("una_tantum", "Una tantum")],
                        default="annuale",
                        max_length=20,
                    ),
                ),
                ("descrizione", models.TextField(blank=True)),
            ],
            options={"ordering": ["nome"],},
        ),
        migrations.CreateModel(
            name="TipoScadenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo scadenza",
                "verbose_name_plural": "Tipi scadenza",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EdizioneProgetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField(blank=True, null=True)),
                ("titolo", models.CharField(blank=True, max_length=255)),
                ("una_tantum", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "progetto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edizioni",
                        to="core.progetto",
                    ),
                ),
            ],
            options={"ordering": ["progetto__nome", "anno"],},
        ),
        migrations.CreateModel(
            name="Scadenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("da_fare", "Da fare"),
                            ("in_corso", "In corso"),
                            ("fatto", "Fatto"),
                            ("in_attesa", "In attesa"),
                            ("da_chiarire", "Da chiarire"),
                        ],
                        default="da_fare",
                        max_length=20,
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("bassa", "Bassa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("data_avvio", models.DateField(blank=True, null=True)),
                ("data_scadenza", models.DateField(blank=True, null=True)),
                ("data_conclusione", models.DateField(blank=True, null=True)),
                (
                    "importo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edizione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scadenze",
                        to="core.edizioneprogetto",
                    ),
                ),
                (
                    "ente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scadenze",
                        to="core.ente",
                    ),
                ),
                (
                    "responsabili",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scadenze_assegnate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scadenze",
                        to="core.tiposcadenza",
                    ),
                ),
            ],
            options={"ordering": ["data_scadenza", "titolo"],},
        ),
        migrations.AddConstraint(
            model_name="edizioneprogetto",
            constraint=models.UniqueConstraint(
                fields=("progetto", "anno"), name="unique_progetto_anno"
            ),
        ),
    ]
