# Generated by Django 5.2.12 on 2026-04-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Soggetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Soggetto",
                "verbose_name_plural": "Soggetti",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="edizioneprogetto",
            options={
                "ordering": ["progetto__nome", "anno"],
                "verbose_name": "Edizione progetto",
                "verbose_name_plural": "Edizioni progetto",
            },
        ),
        migrations.AlterModelOptions(
            name="ente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Ente",
                "verbose_name_plural": "Enti",
            },
        ),
        migrations.AlterModelOptions(
            name="progetto",
            options={
                "ordering": ["nome"],
                "verbose_name": "Progetto",
                "verbose_name_plural": "Progetti",
            },
        ),
        migrations.AlterModelOptions(
            name="scadenza",
            options={
                "ordering": ["data_scadenza", "titolo"],
                "verbose_name": "Scadenza",
                "verbose_name_plural": "Scadenze",
            },
        ),
        migrations.AlterModelOptions(
            name="tiposcadenza",
            options={
                "ordering": ["nome"],
                "verbose_name": "Tipo scadenza",
                "verbose_name_plural": "Tipi scadenze",
            },
        ),
        migrations.AddField(
            model_name="scadenza",
            name="soggetto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scadenze",
                to="core.soggetto",
            ),
        ),
    ]
