# Generated by Django 5.2.12 on 2026-04-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_soggetto_alter_edizioneprogetto_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="scadenza", name="soggetto",),
        migrations.AddField(
            model_name="progetto",
            name="soggetto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scadenze",
                to="core.soggetto",
            ),
        ),
    ]
