# Generated by Django 5.2.12 on 2026-04-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_scadenza_soggetto_progetto_soggetto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scadenza",
            options={
                "ordering": ["data_scadenza"],
                "verbose_name": "Scadenza",
                "verbose_name_plural": "Scadenze",
            },
        ),
        migrations.RemoveField(model_name="scadenza", name="titolo",),
    ]
