# Generated by Django 5.2.12 on 2026-04-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_scadenza_options_remove_scadenza_titolo"),
    ]

    operations = [
        migrations.RemoveField(model_name="edizioneprogetto", name="titolo",),
        migrations.AlterField(
            model_name="progetto",
            name="soggetto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progetti",
                to="core.soggetto",
            ),
        ),
    ]
