# Generated by Django 5.2.12 on 2026-04-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_edizioneprogetto_titolo_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="scadenza", name="data_conclusione",),
    ]
